tools/vqgan/create_train_split.py

Currently `tools/vqgan/create_train_split.py` uses a hardcoded 100 samples of val set to split train vs val set.
This will cause an issue for dataset <= 100 samples, and perform badly for dataset <= 200 samples.
This pr changed the split to a ratio of 3:1 (3 training samples vs 1 validation sample), and will hopefully fix this problem.

Use a ratio to split train vs val set in tools/vqgan/create_train_split.py

---

data_server/build.rs

> it is recommended that every build script emit at least one of the rerun-if instructions
see: https://doc.rust-lang.org/cargo/reference/build-scripts.html#change-detection

Rerun build only if proto file chaged

---

tools/llama/generate.py

for example "据海关统计，今年前4个月，我国货物贸易进出口总值13.81万亿元，同比增长5.7%， 其中，出口7.81万亿元，增长4.9%，进口6万亿元，增长6.8%。"
#xxx

The decimal point will be split into two sentences, will be cut off from the middle.

---

fish_speech/configs/vits_decoder_finetune.yaml
fish_speech/configs/vits_decoder_pretrain.yaml

Fix BUG.
在部分Ampere GPU上，开启此选项会导致异常的速度损失（>90%）和GPU Memory占用波动。因此默认关闭

默认关闭cudnn benchmark

---

tools/llama/generate.py
tools/vits_decoder/inference.py

Fix: (1).output wav cascaded when num_samples>1; (2). Wrong config name for vits_decoder.
Fix BUG.
No.

Fix bug on inference

---

tools/llama/merge_lora.py

Fix BUG.
#281
If "state_dict" is not in llama_state_dict, and the keys in llama_state_dict do not start with "model.", the filtered dictionary will end up empty D:

Fix: state dict may exclude keys during lora merging

---

docs/ja/finetune.md
docs/ja/index.md
docs/ja/inference.md
docs/ja/samples.md
mkdocs.yml

I created Japanese translated documents.

docs: add Japanese translations to docs

---

README.md
README.zh.md

This pull request is a fix for the Portuguese readme.md path, which is incorrect.
Someone put README.pt-BR instead of README.pt-BR.md in the README.md and README.zh.md documents.

Fix português (brasil) README.md path

---

tools/vqgan/inference.py

This pull request addresses an issue in tools/vqgan/inference.py where the import statement for AUDIO_EXTENSIONS was incorrect. The import statement was originally:
```python
from fish_speech.utils.file import AUDIO_EXTENSIONS
```
It has been updated to:
```python
from tools.file import AUDIO_EXTENSIONS
```

 Fix Import Path in tools/vqgan/inference.py

---

tools/llama/generate.py

Fix BUG.
When running inference on CPU (I'm running this on M1 Pro Macbook), installed torch may lack compiled-in cuda support altogether, resulting in `module 'torch.backends' has no attribute 'sdp_kernel'` error. `--device cpu` command line flag correctly deals with all situation except this one, so check here for cuda availability explicitly.

Avoid cuda-dependent code for CPU-only inference

---

tools/llama/build_dataset.py

Fix BUG.
**Is this pull request related to any issue?**
No
Corrects an invalid reference after the function `load_filelist` was moved to `tools.file`, resolving runtime errors.

Fix reference to load_filelist

---

pyproject.toml

following the install step,  install pytorch first ,then the dependency of project. pytorch will reinstalled if the version isn't 2.3.1. 
it will also trick a bug by dependency resolver. 
```
Attempting uninstall: triton
Found existing installation: triton 3.0.0
Uninstalling triton-3.0.0:
Successfully uninstalled triton-3.0.0
Attempting uninstall: nvidia-cudnn-cu12
Found existing installation: nvidia-cudnn-cu12 9.1.0.70
Uninstalling nvidia-cudnn-cu12-9.1.0.70:
Successfully uninstalled nvidia-cudnn-cu12-9.1.0.70
Attempting uninstall: numpy
Found existing installation: numpy 2.1.1
Uninstalling numpy-2.1.1:
Successfully uninstalled numpy-2.1.1
Attempting uninstall: fsspec
Found existing installation: fsspec 2024.9.0
Uninstalling fsspec-2024.9.0:
Successfully uninstalled fsspec-2024.9.0 …
```

Fix BUG pytorch dependency resolver

---

tools/api.py

"sox" backend does not support reading from file
(this is a very basic, "caveman" fix)
Fix BUG.

replace "sox" backend for reference_audio

---

README.ja.md
README.md
README.zh.md

Fix BUG.
No
1. The src of docker icon is wrong.
2. jp README shows the file is in English, and it should be center-aligned.
3. "中文简体" is wrong in Simplified Chinese expression, the properer one is "简体中文“

Fix: Docker icon is missing in zh-cn README & ja README displays that it is in English & properer expression “简体中文”

---

README.ja.md
README.md
README.pt-BR.md
README.zh.md
docs/en/index.md
docs/ja/index.md
docs/pt/index.md
docs/zh/index.md
install_env.bat
pyproject.toml
tools/api.py
tools/commons.py
tools/post_api.py

1. Fix the problem that uvicorn can't start multiple workers, now support api to start multiple workers, increase throughput to achieve concurrent operation. Throughput is limited by GPU core count and utilisation. Sample command in the project root directory: `python -m tools.api --compile --workers 4`
2. Support for caching the results of reference audio encoding in memory, for cases where a single speaker does not change it for a long time, reducing latency. This parameter adds a field for `use_memory_cache` to the request parameter of post_api. If `use_memory_cache` is set to `on-demand`, then the cache will always be used after the first encoding, regardless of any subsequent reference audio. If you want to change …

feat: enable more workers in `api.py`

---

fish_speech/models/vqgan/modules/firefly.py

This is a developer-side bug fix that addresses an issue with VQGAN parameterization removal. This bug does not affect end users under normal circumstances, as `remove_parameterization` is not used in any other part of the codebase.
The following code (forked from `tools/vqgan/inference.py`) triggers the error:
```python
model: FireflyArchitecture = load_model(config_name, checkpoint_path, device=device)
model.remove_parametrizations()
```
Error message:
```
ValueError: Module FishTransConvNet(
(conv): ParametrizedConvTranspose1d(
512, 256, kernel_size=(16,), stride=(8,)
(parametrizations): ModuleDict(
(weight): ParametrizationList(
(0): _WeightNorm()
)
)
)
) does not have a parametrization on weight
```
**Is this pull request related to any …

Fix broken `remove_parameterization` in firefly

---

tools/llama/generate.py

Fix BUG.
Currently when you try to clone a voice to do TTS, every sentence starts with "Speak" because this gets prepended when passing to the model. Getting rid of this token makes them all work.
To give you an idea of how bad this is, here's an example generated audio clip in Japanese (Same thing happens in other languages as well, such as Korean):
https://github.com/user-attachments/assets/d54b554f-4d13-421d-983e-56653c71b396
```
とつぜん の キス や あつい まなざし で
こい の プログラム を くるわせないで ね
であい と わかれ じょうず に うちこんで
じかん が くれ ば おわる Don’t hurry!
あい に きずついた あの ひ から ずっと
ひる と よる が ぎゃく の くらし を つづけて
はやり のDisco で おどりあかす うち に
おぼえた まじゅつ な の よ I ‘m sorry!
```

"Speak" gets prepended to every single utterance.

---

fish_speech/models/vqgan/modules/fsq.py

Let's say `diff=-3` which is negative, then we got `left = diff // 2 =  -2` and `right = diff - left = -1`.
The correct cropping operation should be `result.z[..., 2:-1]` instead of `result.z[..., -2:1]`

Fix original shape matching with crop

---

pyproject.toml

fix: https://github.com/fishaudio/fish-speech/issues/660
When running the docker image ```ModuleNotFoundError: No module named 'cachetools' ```will appear. Therefore, add the cachetools package to the stable dependency group.

fix: Install cachetools dependencies

---

tools/api.py
tools/webui.py

Fix for #691 
The argument parsers of the webui and the postapi default `device` to `cuda` but never checks if CUDA is actually available.
This is a very small fix to default to CPU if `torch.cuda.is_available()` is `False`.

fix CPU use

---

pyproject.toml

The PR removes a dependency duplicate that caused some issues getting started when I was using a conda/pypi derivative.
Below I'm linking the the current dates latest ref for quick access. The first and last line show the dupl
https://github.com/fishaudio/fish-speech/blob/b11bcf834a97a75073b535838e5f0765f169eb94/pyproject.toml#L22-L33

Remove dependency duplicate

---

tools/run_webui.py
tools/server/model_manager.py

Fix BUG.
This pull request fixes the faulty logic from https://github.com/fishaudio/fish-speech/pull/714/files which would have never worked as the secondary CUDA check would have overridden the device with "cpu" every time.

Fixed faulty mps device checking logic

---

tools/api_client.py

Fix BUG.
N/A
**Description**
Currently, `--play` has no effect because its default value is `True`. The parser does not recognize anything like `--play False`. It only detect whether the argument exists.
Therefore, we can use [BooleanOptionalAction](https://docs.python.org/3/library/argparse.html#argparse.BooleanOptionalAction), which automatically add the `--no-play` option, so that the play argument can be set to `False`.
**Compatibility**
This change does not break the existing behaviors because it adds a new option.

fix: no-play argument for API client

---

docs/en/inference.md
docs/ja/inference.md
docs/ko/inference.md
docs/pt/inference.md
docs/zh/inference.md

Fix BUG (Documentation improvement).
No related issue.
---
https://github.com/fishaudio/fish-speech/commit/62eae262c20d5a83db5c825383993d548f82b813
This commit from last week on the PR has made several changes, and as someone who is just getting familiar with the project, I found that I couldn't successfully start the web UI based on the documentation.  
After some investigation, I pinpointed the issue—I was supposed to use `tools.run_webui` instead of `tools.webui`.  
Once I made that change, everything worked as expected.  
The purpose of my current PR is to improve the documentation so that future users can more easily start the web UI. Honestly, I really enjoy …

fix: update command to start WebUI in documentation

---

tools/api_client.py
tools/api_server.py
tools/server/api_utils.py

Add feature.
N/A
**Description**
In tools/api_client.py, it already implements the header for bearer auth. This PR is to complete the configurations for this feature.
**Details**
- tools/api_client.py
- Add argument `--api_key` to specify the authentication token.
- The default value is "YOUR_API_KEY", which remains the previous behavior.
- tools/server/api_utils.py
- Add argument `--api_key` to specify the authentication token.
- tools/api_server.py
- Add a middleware to verify the `api_key` if it is provided.
**Compatibility**
If the new arguments are not specified, the previous behavior will not change.

feat: Bearer auth for HTTP API

---

tools/llama/build_dataset.py

Fix BUG
N/A
The `load_filelist` function was incorrectly imported from `fish_speech.datasets.protos.text_data_stream` when it has been moved to `fish_speech.utils.file`. This PR updates the import statement to use the correct path.
Changes:
- Remove import of `load_filelist` from text_data_stream
- Add import of `load_filelist` from fish_speech.utils.file
This fixes potential import errors and maintains consistency with the current project structure.

Fix: Update incorrect import path for load_filelist function

---

fish_speech/models/vqgan/modules/firefly.py
fish_speech/utils/spectrogram.py
tools/export-onnx.py

Fix BUG:
- tracer of pytorch could not trace any non-torch types, include python builtin types, math.ceil() will cast a scalar tensor to a python builtin scalar, it will become constant in onnx graph and cause error on outputs.

fix bugs in onnx tracer

---

tools/api_server.py

Fix BUG. as I think uvicorn is support both v4 and v6, but   `host, port = api.args.listen.split(":")` this line will fail to split v6 host. because there are many `:` in ipv6 address. many china user not have public ipv4 but easy to get public ipv6. 
no
-------
or one regular expression could fix it, I just encounter this problem and try to fix it. 
```python3
pattern = r'(?:\[([^\]]+)\]|([^:]+))?:(\d+)$'
match = re.search(pattern, api.args.listen)
ipv6, ipv4, port = match.groups()
host = ipv6 or ipv4
```

support ipv6

---

tools/server/views.py

Fix bug.
This pull request is not related to any issue.
**Description of the fix:**
The `/health` API endpoint was originally using the `POST` method, which is not ideal for a health check. This PR adds a new `/health` endpoint with the `GET` method while keeping the existing `POST` method for backward compatibility.

Add method GET on route `/health`

---

tools/api_server.py

Fix BUG.
I think the argument “--api-key” in api_server.py is currently not working.
I checked the source code,
Since the api_auth() method is not used,
I added it to the middleware.

Fix: “--api-key” argument in api_server.py does not work

---

tools/llama/merge_lora.py

I had been fine-tuning Fish-speech on my custom Hebrew dataset and while doing so, I encountered a issue that comes with recent pytorch version where `weights_only=True` by default and it was breaking **merge_lora.py** file from working properly. I tested after switching it to False and now it works. 
Would love this is incorporated in the default code so that me and others don't have manually switch it back off. Because it is simply a security reason than being a performance issue.

changed weights_only=True to false to override security concerns

---

fish_speech/inference_engine/reference_loader.py

Fix BUG.
#xxx
Fixed a bug where the whole list was being cached — now it only stores the current item.
This bug used to mess up the cache structure when handling multiple reference audios.

fix: fixed hash cache logic error in ReferenceLoader
