tools/whisper_asr.py
- 1.There were some path issues with yesterday's whisper_asr conversion script, which I have now fixed.
- 2.According to the documentation guide at https://speech.fish.audio/, the conversion script now also supports transcription of audio in all formats (FLAC, MP3, WAV).
=> 1.Supports FLAC, WAV, MP3  2.Fixed conversion path issue.

fish_speech/text/chinese.py, pyproject.toml
[#21](https://github.com/fishaudio/fish-speech/issues/21)
=> replace cn2an with WeTextProcessing for text normalization

tools/api_server.py
=> Optimize kui usage

data_server/src/main.rs, tools/api_server.py, tools/merge_asr_files.py, tools/whisper_asr.py
=> Merge update into dev

data_server/Cargo.lock, data_server/Cargo.toml, data_server/src/main.rs
Make file loading parallelized in `MyDataService::new`
=> Parallelized loading in MyDataService::new

fish_speech/utils/file.py, tools/vqgan/extract_vq.py
=> Improve file list and vq performance

fish_speech/webui/html/footer.html, fish_speech/webui/launch_utils.py
=> fix: change repo url to the right one (AnyaCoder -> fishaudio)

fish_speech/i18n/locale/ja_JP.json, fish_speech/webui/manage.py
=> Fix button height

docs/en/inference.md, docs/zh/inference.md
按照操作说明，会run不起来，少了这个firefly-gan-base-generator.ckpt的下载
#xxx
=> add  firefly-gan-base-generator.ckpt model download command to doc

tools/webui.py
=> Fix error info

fish_speech/i18n/locale/en_US.json, fish_speech/i18n/locale/es_ES.json, fish_speech/i18n/locale/ja_JP.json, fish_speech/i18n/locale/zh_CN.json, fish_speech/webui/manage.py
> [!NOTE]
> This PR modified `fish_speech/webui/manage.py`  to improve the user experience when setting the inference models.
> 这一 PR 主要修改了  `fish_speech/webui/manage.py`  以提升设置推理服务器配置时的用户体验.
> [!CAUTION]
> **Fix BUG**
> - The step of `from fish_speech import xxx` must come after `sys.path.insert()` to ensure the successful import.
>
> **修复问题**
> - `from fish_speech import xxx` 这一步应放置在 `sys.path.insert()` 之后以确保正确导入.
> [!TIP]
> **Add Feature** 
> 1. Add warning information in the terminal if there is no available model in local dirs.
> 2. Add `list_llama_model()` to allow users to choose from available LLaMA model paths.
> 3. Add two functions (`change_llama_config`, `change_decoder_config()`) to change the config of the model according to …
=> Improve WebUI Inference Server Configuration Interaction

start.bat, tools/download_models.py
=> Automatically download models

fish_speech/webui/manage.py
=> select is not lora

.github/workflows/build-windows-package.yml
=> New Package Logic

.github/workflows/build-windows-package.yml, install_env.bat
=> Update Batch File: Ensure ASCII

tools/vqgan/create_train_split.py
修改成和47行一样的为相对root的目录，不然后面vits微调读不到数据，dataloader出来长度为0
=> 修改成和47行一样的为相对root的目录

tools/whisper_asr.py
更新 `tools/whisper_asr.py` 的使用命令的参数
`audio_dir` -> `audio-dir`
`save_dir` -> `save-dir`
=> fix(tools/whisper_asr): use example

tools/webui.py
Add feature.
#187 
Now can use `--device "mps" ` to accelerate inference speed in Mac device. 
现在可以使用`--device "mps"`来加快在Mac上的推理速度
=> Apple's MPS backend support

install_env.bat
Optimize Windows Compile, @AnyaCoder
=> Optimize Windows Compile

docs/en/index.md, docs/zh/index.md
=> Add Windows Setup Help

tools/webui.py
=> 流式推理音频添加下载按钮

docs/en/finetune.md, docs/en/index.md, docs/en/inference.md, docs/zh/finetune.md, docs/zh/index.md, docs/zh/inference.md
=> Modify the documents

docs/en/index.md, docs/ja/index.md, docs/zh/index.md
Fix BUG.
Fixed a few images, now `/docs/zh/index.md` can display them correctly
=> [docs] 修复了几个图片. Fixed a few images

pyproject.toml
=> fix modelscope version problem

tools/webui.py
Add parameters for theme color
Add feature 
no
=> Add parameters for theme color

inference.ipynb, pyproject.toml, tools/auto_rerank.py, tools/download_models.py, tools/webui.py
Fix BUG.
add webui option to enable/disable asr models
=> Fix around asr bugs

fish_speech/models/text2semantic/llama.py
=> Add preprocessing and validation steps when loading the checkpoint.

pyproject.toml
=> Fix：(req) add torchaudio req

docs/zh/index.md
Add Docs:
#346 #247 
**Test**
1. Run image and download model
2. Check model file
3. Export GRADIO_SERVER_NAME and Run WebUI
4. Open WebUI page and test generate
=> Docs: Update docker configuration

docs/ja/index.md
Neither
I just rewrote some of the Japanese expressions and grammar that bothered me.
=> chore: retranslate ja/index.md

.github/workflows/build-windows-package.yml, docs/en/index.md, docs/ja/index.md, docs/pt/index.md, docs/zh/index.md, install_env.bat, pyproject.toml
avoid many problems caused by auto-installing torch >= 2.4.0
=> Fix win deps

tools/post_api.py
=> more stable streaming audio play and save

pyproject.toml
=> Fix(deps): remove audio-seperator

README.md
=> Update README.md, add trending

pyproject.toml, tools/api.py, tools/commons.py, tools/msgpack_api.py, tools/post_api.py
=> fully support ormsgpack

README.md, README.pt-BR.md, README.zh.md
=> Upload V1.4 Demo Url

README.ja.md, README.pt-BR.md, README.zh.md
I created Japanese translated README.
=> docs: add Japanese README

tools/llama/generate.py
Fix BUG.
https://github.com/fishaudio/fish-speech/issues/537
=> Context length reading configuration file

.dockerignore, .github/workflows/build-dev.yml, .github/workflows/build-linux-image.yml, Dockerfile-debug, dockerfile, entrypoint.sh
- feat: bump **python** from **3.10** to **3.12**
- ~~feat: dependency management with python poetry~~
- feat: support for **linux/arm64**
- ~~perf: optimize image size(use poetry).  ~~11.1GB~~ to **2.93GB**~~
- perf: optimize image size(use pip).  ~~11.1GB~~ to **3.28GB**
- perf: optimizing **actions** build
```sh
docker buildx build -t ghcr.io/fishaudio/fish-speech/fish-speech:dev . --load
docker buildx build -t ghcr.io/fishaudio/fish-speech/fish-speech:dev-debug -f Dockerfile-debug . --load
docker run --name fish-speech -d -p 7860:7860 ghcr.io/fishaudio/fish-speech/fish-speech:dev
docker run --name fish-speech -d -p 7860:7860 -e CUDA_ENABLED=0 ghcr.io/fishaudio/fish-speech/fish-speech:dev
docker run --name fish-speech -p 7860:7860 -it ghcr.io/fishaudio/fish-speech/fish-speech:dev-debug …
```
=> perf: Optimizing docker builds

.github/workflows/build-dev.yml, .github/workflows/build-linux-image.yml, .github/workflows/docs.yml, Dockerfile-debug
- ~~fix: actions build error [**No space left on device**](https://github.com/fishaudio/fish-speech/actions/runs/10866966093)~~
- fix: fork repository build failure
- perf: document build is only triggered when the document is modified
=> fix: actions build error

docs/en/inference.md, docs/ja/inference.md, docs/pt/inference.md, docs/zh/inference.md, fish_speech/i18n/locale/en_US.json, fish_speech/i18n/locale/es_ES.json, fish_speech/i18n/locale/ja_JP.json, fish_speech/i18n/locale/zh_CN.json, tools/webui.py
=> Add Audio Select to WebUI

README.ja.md, README.md, README.pt-BR.md
=> docs: Corrected the wrong expressions of supported languages in README

tools/api.py
=> Api json format

tools/post_api.py
=> chore: typo fix on post_api

tools/webui.py
=> Fix streaming output in webui

Start_Agent.md, tools/fish_e2e.py
=> Add details about how to start agent.

tools/e2e_webui.py
=> fix e2e_webui

pyproject.toml
=> Fix VQ Pytorch version

README.md
=> Add QQ Channel link

tools/api.py, tools/webui.py
=> Update V1.5 WebUI

tools/inference_engine/reference_loader.py, tools/run_webui.py, tools/server/model_manager.py
=> #fix 1)enable mps device 2) fix bug in reference audio scenario

pyproject.toml, tools/api_client.py, tools/download_models.py, tools/inference_engine/__init__.py, tools/inference_engine/reference_loader.py, tools/inference_engine/utils.py, tools/run_webui.py, tools/server/inference.py, tools/server/model_manager.py
=> fix: tts reference and config

tools/inference_engine/reference_loader.py
=> fix: cache reference by hash (#730)

API_FLAGS.txt, dockerfile, docs/pt/inference.md, tools/llama/generate.py, tools/vqgan/extract_vq.py, tools/vqgan/inference.py
=> Switch default checkpoint version to 1.5

tools/api_server.py, tools/schema.py, tools/server/views.py
**BUG?**
refactor code to fix openapi doc
**before the fix**
**after the fix**
=> refactor: openapi doc

tools/schema.py
=> Fix ServeReferenceAudio to allow base64 reference data in json

fish_speech/configs/text2semantic_finetune.yaml, fish_speech/datasets/semantic.py
Add normal dataset class to load dataset
=> [feature]add dataset classs

docs/en/index.md
Prevent MacOS clang compile error. Please remember to update other language.
Fix BUG.
No
=> Update English index.md

tools/export-onnx.py
Add feature:
- add onnx export code for vqgan decoder model
Todo:
- add onnx export code for vqgan encoder model and llama
=> add onnx export code for vqgan model

fish_speech/utils/spectrogram.py, tools/export-onnx.py
Add feature:
- add onnx export code for vqgan encoder
=> add onnx export code for vqgan encoder

tools/download_models.py
**this PR Is fix a BUG**
Modify the correct automatic download path, otherwise an error 404 will be reported
#Yin-Shang
=> Modify the correct automatic download path, otherwise an error 404 will be reported

docs/en/start_agent.md
Replace "yout" with "your" in environment setup guide
=> Fix: correct typo

install_env.bat
=> Add mirrors for torch

fish_speech/models/text2semantic/inference.py
use `torch.nn.attention.sdpa_kernel()` instead of `torch.backends.cuda.sdp_kernel()`
to avoid:
```bash
FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated. In the future, this context manager will be removed. Please see `torch.nn.attention.sdpa_kernel()` for the new context manager, with updated signature.
```
This `FutureWarning` only exist in `Windows WSL`
I have tested in `MacOS`, this PR has no side effect.
---
btw: which formatter you are using in `VSCode`?
=> Fixed: FutureWarning: `torch.backends.cuda.sdp_kernel()` is deprecated.

fish_speech/models/text2semantic/inference.py
=> Fix inference speed.

fish_speech/text/clean.py
=> fix: rollback clean.py

fish_speech/content_sequence.py, fish_speech/models/text2semantic/inference.py, fish_speech/models/text2semantic/llama.py
Fix BUG.
We fixed a existed audio quality bug for long seqence.
=> Fix audio quality bug

docs/en/install.md, docs/ja/install.md, docs/ko/install.md, docs/pt/install.md, docs/zh/install.md, tools/run_webui.py
Add feature.
Intel Arc GPUs support using PyTorch's native implementation, requiring only minimal code changes.
Tested on an Intel Arc B580 (12 GB).
#xxx
=> Intel arc XPU support
